services:
  - type: web
    name: ai-career-navigator-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar -Dspring.profiles.active=prod target/ai-career-navigator-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: aicareernavigator
      - key: JWT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://ai-career-navigator-orcin.vercel.app
