services:
  - type: web
    name: ai-career-navigator-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: aicareernavigator
      - key: JWT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://ai-career-navigator-orcin.vercel.app
